language: go
go:
- 1.5.1
- tip
addons:
  apt:
    packages:
    - upx-ucl
env:
- GOOS=linux
before_script:
- mkdir -p dst
- go get github.com/pwaller/goupx
script:
- GOARCH=amd64 go build -o dst/ImageService-amd64-$(go version | awk '{print $3}') $(find . -type f -name '*.go')
- GOARCH=arm go build -o dst/ImageService-arm-$(go version | awk '{print $3}') $(find . -type f -name '*.go')
- goupx $(find dst -type f)
- gem install mime-types -v 2.5
notifications:
  webhooks:
  - https://exchange.vitalvas.com/api/hooks.json?tag=go-http-upload
deploy:
  provider: gcs
  access_key_id: GOOG6CIQYT537FCFGQJC
  secret_access_key:
    secure: DIlO+wYEedf7LBwWVR3918zX7TGF/IsGjJ2VopWZoOkWBItKH37if3UbffbJr4naVhPQnLr14ZD7eWKPhi9TGpSjGMYOCb+psYiA7b8kXokJW4EJCCH1NcV3jaT+D2SLo46irR96JsKv5hOZMe+jdnmpIqeCJg/ITR4+54sefTS105UpbHsT2gGBJnO75n2ASdvjbg2Dx1a7007pcnIg9tguxEqdmIDHlJ70RCWB3zWoEBzWzYDkiOlmpmfbMU0gy3wnJD5jjAC5/lt3oFJDp2EDX/XwWtL3Lv3Cfc51LoZkaAivaQZCtJmJsRnQXMfNg4oLD6IutCxH/ktHJy6Lr4Jm2WBAG2fHT6uDjOkonGPx6tRGwYGdc5q84AH1RHmC5DItlP1XfeGAZkMWccv3H7EqnISZebGA2TH3UTylTWJw3C1wMPO2GS32GBjZF5N5PQPN4BgR2+OPk4qvJXnM19t1/X0acaW4/flezEjisaGwjaOItdqd5ZAnOAAzbuboayCaXU1s0uvZc6Oub3pgmuFcUEKoxnFNPZlw0l5wuQFmGEjGCvH/uLBlRlPfufcCQKqAWVY9rcKdy0vPb1XfoWSQzYZMjKlkm6NCSplQvW1+20B5HrlYust/wR+IWXua+zsrOq1N3Iyb76dk4h6ZMxTE1L3Ff5gTFJShtVF5CeM=
  bucket: xs-services
  local-dir: dst
  skip-cleanup: true
  on:
    repo: vitalvas/go-http-upload
    branch: master
matrix:
  allow_failures:
  - go: tip
